spring.application.name=fastcommerce
spring.datasource.url=jdbc:postgresql://localhost:5432/fastcommerce
spring.datasource.username=postgres
spring.datasource.password=159753
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true